# fly.toml file generated for solitary-sun-529 on 2023-02-09T18:57:28-03:00

app = "solitary-sun-529"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
auto_rollback = true

[deploy]
strategy = "bluegreen"


[checks]

[checks.nats]
grace_period = "60s"
interval = "15s"
port = 4222
timeout = "5s"
type = "tcp"

# [[services]]
# http_checks = []
# internal_port = 4222
# processes = ["app"]
# protocol = "tcp"
# script_checks = []

# [services.concurrency]
# hard_limit = 25
# soft_limit = 20
# type = "connections"

# [[services.ports]]
# force_https = true
# handlers = ["http"]
# port = 80

# [[services.ports]]
# handlers = ["tls", "http"]
# port = 443

# [[services.tcp_checks]]
# grace_period = "15s"
# interval = "15s"
# restart_limit = 0
# timeout = "2s"
